version: "2.38.1"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    networks:
      - app-net

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      # - BACKEND_URL=https://backend:8080
      # - NODE_TLS_REJECT_UNAUTHORIZED=0
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
