version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./front-end/public/uploads:/app/../front-end/public/uploads

  frontend:
    depends_on:
      - backend
    build:
      context: ./front-end
    ports:
      - "3000:3000"
