[build]
  cmd = "go build -o ./tmp/main"
  bin = "tmp/main"
  full_bin = "tmp/main"
  include_ext = ["go","sql"]
  exclude_dir = []

[include]
  # Only watch these directories
  paths = [
    "./main.go",
    "./app/",
    "./go.mod/"
  ]