[build]
  cmd = cmd = "pkill -x ./tmp/main || echo 'No running process to kill'; sleep 1;rm -f tmp/main && go build -o ./tmp/main1 main.go"
  bin = "tmp/main1"
  kill_delay = 1000
  include_ext = ["go","sql"]

[include]
  # Only watch these directories
  paths = [
    "main.go",
    "app/",
    "go.mod"
  ]